export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAILURE = 'GET_USER_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const LOGOUT = 'LOGOUT';

export const POST_TASK_REQUEST = 'POST_TASK_REQUEST';
export const POST_TASK_SUCCESS = 'POST_TASK_SUCCESS';
export const POST_TASK_FAILURE = 'POST_TASK_FAILURE';
export const POST_TASK_RESET = 'POST_TASK_RESET';

export const GET_TASKS_REQUEST = 'GET_TASKS_REQUEST';
export const GET_TASKS_SUCCESS = 'GET_TASKS_SUCCESS';
export const GET_TASKS_FAILURE = 'GET_TASKS_FAILURE';
export const GET_TASKS_RESET = 'GET_TASKS_RESET';

export const GET_PARTICULAR_TASK_REQUEST = 'GET_PARTICULAR_TASK_REQUEST';
export const GET_PARTICULAR_TASK_SUCCESS = 'GET_PARTICULAR_TASK_SUCCESS';
export const GET_PARTICULAR_TASK_FAILURE = 'GET_PARTICULAR_TASK_FAILURE';

export const POST_OFFER_REQUEST = 'POST_OFFER_REQUEST';
export const POST_OFFER_SUCCESS = 'POST_OFFER_SUCCESS';
export const POST_OFFER_FAILURE = 'POST_OFFER_FAILURE';
export const POST_OFFER_RESET = 'POST_OFFER_RESET';

export const GET_OFFERS_REQUEST='GET_OFFER_REQUEST';
export const GET_OFFERS_SUCCESS='GET_OFFER_SUCCESS';
export const GET_OFFERS_FAILURE='GET_OFFER_FAILURE';
export const GET_OFFERS_UPDATE='GET_OFFER_UPDATE';


export const UPDATE_OFFER_REQUEST='UPDATE_OFFER_REQUEST';
export const UPDATE_OFFER_SUCCESS='UPDATE_OFFER_SUCCESS';
export const UPDATE_OFFER_FAILURE='UPDATE_OFFER_FAILURE';

export const COMPLETE_TASK_REQUEST='COMPLETE_TASK_REQUEST';
export const COMPLETE_TASK_SUCCESS='COMPLETE_TASK_SUCCESS';
export const COMPLETE_TASK_FAILURE='COMPLETE_TASK_FAILURE';
export const COMPLETE_TASK_RESET='COMPLETE_TASK_RESET';

export const GET_MY_TASKS_REQUEST='GET_MY_TASKS_REQUEST';
export const GET_MY_TASKS_SUCCESS='GET_MY_TASKS_SUCCESS';
export const GET_MY_TASKS_FAILURE='GET_MY_TASKS_FAILURE';

export const SOCKET_CONNECTED = 'SOCKET_CONNECTED';
export const SOCKET_DISCONNECTED = 'SOCKET_DISCONNECTED';

export const GET_CHATS_REQUEST='GET_CHATS_REQUEST';
export const GET_CHATS_SUCCESS='GET_CHATS_SUCCESS';
export const GET_CHATS_FAILURE='GET_CHATS_FAILURE';
export const SET_CHATS_UPDATE='SET_CHATS_UPDATE';

export const GET_MESSAGES_REQUEST='GET_MESSAGES_REQUEST';
export const GET_MESSAGES_SUCCESS='GET_MESSAGES_SUCCESS';
export const GET_MESSAGES_FAILURE='GET_MESSAGES_FAILURE';
export const SET_MESSAGES_UPDATE='SET_MESSAGES_UPDATE';
export const SET_MESSAGES_UPDATE_RESET='SET_MESSAGES_UPDATE_RESET';

export const SEND_MESSAGE_REQUEST='SEND_MESSAGE_REQUEST';
export const SEND_MESSAGE_SUCCESS='SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_FAILURE='SEND_MESSAGE_FAILURE';
export const SEND_MESSAGE_RESET='SEND_MESSAGE_RESET';

export const SET_ONLINE_USERS='SET_ONLINE_USERS';

export const GET_ALERT_REQUEST='GET_ALERT_REQUEST';
export const GET_ALERT_SUCCESS='GET_ALERT_SUCCESS';
export const GET_ALERT_FAILURE='GET_ALERT_FAILURE';
export const GET_ALERT_UPDATE='GET_ALERT_UPDATE';


